version: '3'
services:
  test-docker:
    container_name: "test-docker-container"
    build:
     context: .
     target: ${mood}
    volumes:
    - './src:/app/src:ro'
    ports:
    - "4000:4000"
    env_file:
    - ./.env
    depends_on:
      - mongo-express
    # environment:
    # - name=${basUrlName}
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    #environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: Admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: Admin123
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      # ME_CONFIG_BASICAUTH: false
  nginx:
   image: nginx:stable-alpine
   ports:
    - "80:80"
   volumes:
    # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
   depends_on:
    - test-docker
volumes:
  mongo-db: